# Generated by Django 5.2.4 on 2025-09-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_car_is_available_car_slug_alter_car_car_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
