# Generated by Django 5.2.4 on 2025-09-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_alter_car_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='Car_images/'),
        ),
    ]
