# Generated by Django 5.2.4 on 2025-09-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_address_order_card_name_order_card_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='order',
            name='expiry',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
